feat: namewrapper update
ensdomains/ensjs-v3 pull request #101
Opened 2023-01-17 06:21 UTC by TateB

- added expired names to test suite
- renamed `burnFuses` to `setFuses`
- added `setChildFuses`
- removed `wrapperExpiry` references from registration related functions
- simplified fuse types
- updated contracts

2023-01-18 08:22 UTC, jefflau requested changes

2023-01-18 08:22 UTC, jefflau commented on packages/ensjs/src/functions/renewNames.ts
> +  return nameWrapper.populateTransaction.extendExpiry(
If we're switching this file to use extendExpiry. Should we rename the name of this file? Renew also exists on the wrapper and renews .eth names. Do we have a function that also deals with renewing .eth names?

2023-01-18 08:23 UTC, jefflau commented
Do we have a function in ensjs to check if a name is wrapped or not?

2023-01-18 08:26 UTC, TateB commented on packages/ensjs/src/functions/renewNames.ts
> +  return nameWrapper.populateTransaction.extendExpiry(
the default export on the file is the renewNames function, doesn't make sense to change the file name because that is still the default export (renews .eth names)

2023-01-18 08:33 UTC, TateB commented
> Do we have a function in ensjs to check if a name is wrapped or not?

`getOwner` checks everything required for checking if a name is wrapped, if it is the ownership level will be nameWrapper

2023-01-18 08:46 UTC, jefflau commented on packages/ensjs/src/functions/getOwner.test.ts
> +  it('should return correct ownership level and values for an expired wrapped .eth name', async () => {
I think maybe ownershipLevel: 'registrar', owner: "0x0" might be more appropriate since the name at this point could be registered on the old registrar. Also does expired take into account grace period?

2023-01-18 08:47 UTC, jefflau commented on packages/ensjs/src/functions/getOwner.test.ts
> +  it('should return correct ownership level and values for an expired wrapped .eth name', async () => {
If the name is expired on the .eth registrar but is in grace period, i think the test is correct. If the name is past grace period, it should probably return what i wrote above

2023-01-18 08:48 UTC, jefflau commented on packages/ensjs/src/functions/getOwner.test.ts
> +import { JsonRpcProvider } from '@ethersproject/providers'
This file should have tests for getOwner on subnames.

2023-01-18 22:18 UTC, TateB commented on packages/ensjs/src/functions/getOwner.test.ts
> +  it('should return correct ownership level and values for an expired wrapped .eth name', async () => {
i think the response makes sense, it can't be registered elsewhere since the registrar returns an ownership value of 0x0. the reason the previous owner before expiry is returned is because the name could be in it's grace period.

2023-01-18 22:22 UTC, TateB commented on packages/ensjs/src/functions/getOwner.test.ts
> +  it('should return correct ownership level and values for an expired wrapped .eth name', async () => {
oops your second comment didn't load before i posted before

we could check the expiry, but then that would overlap with `getExpiry()`

2023-01-24 07:14 UTC, LeonmanRolls approved these changes

2023-01-24 21:49 UTC, merged