update deleteSubname and transferSubname
ensdomains/ensjs-v3 pull request #111
Opened 2023-02-07 02:32 UTC by storywithoutend

2023-02-07 15:50 UTC, jefflau requested changes

2023-02-07 15:50 UTC, jefflau commented on packages/ensjs/src/functions/transferSubname.ts
> +  return nameWrapper.populateTransaction.setSubnodeOwner(
Instead of assuming that if the senderAddress is the parent owner , could we not batch the call for the owner with getting the parent owner and make sure the parent name is owned by the sender. Then we can just throw an error if the caller is neither.

2023-02-07 16:10 UTC, jefflau commented on packages/ensjs/src/functions/transferSubname.ts
> +  return nameWrapper.populateTransaction.setSubnodeOwner(
We should probably also check for fuses here and if PCC is already burnt and if so we know we can't call setSubnodeOwner/Record

2023-02-08 00:42 UTC, TateB commented on packages/ensjs/src/functions/transferSubname.ts
> +  return nameWrapper.populateTransaction.setSubnodeOwner(
transferSubname implies the sender is the parent owner, we haven't done a prereq check like that yet

2023-02-08 04:09 UTC, storywithoutend commented on packages/ensjs/src/functions/transferSubname.ts
> +  return nameWrapper.populateTransaction.setSubnodeOwner(
> Instead of assuming that if the senderAddress is the parent owner , could we not batch the call for the owner with getting the parent owner and make sure the parent name is owned by the sender. Then we can just throw an error if the caller is neither.

Currently the context code exists on the front end. We've had discussions about moving it into ensjs before but we didn't get to it in time.

2023-02-09 02:33 UTC, jefflau commented on packages/ensjs/src/functions/transferSubname.ts
> +  return nameWrapper.populateTransaction.setSubnodeOwner(
If we're assuming the parent owner then we should remove `setRecord` calls

2023-02-10 05:58 UTC, jefflau commented on packages/ensjs/src/functions/deleteSubname.ts
> +      if (method === 'setRecord') {
Have you got a test for this override?

2023-02-10 06:02 UTC, jefflau approved these changes

2023-02-10 07:54 UTC, merged