feat: viem v2 support
ensdomains/ensjs-v3 pull request #175
Opened 2024-02-12 23:36 UTC by TateB

2024-02-13 16:26 UTC, lucemans requested changes

2024-02-13 16:26 UTC, lucemans commented on .github/workflows/test.yml
> +        run: pnpm -F @ensdomains/ensjs build
```suggestion
        run: pnpm -F @ensdomains/ensjs build

```

2024-02-20 03:31 UTC, LeonmanRolls approved these changes

2024-02-21 05:28 UTC, ryangoree commented
Thank you @TateB !

2024-04-03 06:12 UTC, merged